version: 0.19.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: nuget restore source\Khala.Messaging.sln
build:
  verbosity: minimal
  project: source\Khala.Messaging.sln
after_build:
test:
  assemblies: '**\*.tests.dll'
artifacts:
- path: '**\Khala.Messaging**.nupkg'