version: 0.19.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: nuget restore source\Khala.Messaging.sln
build:
  verbosity: minimal
after_build:
- cmd: >-
    nuget pack nuget\Khala.Messaging.Contracts.nuspec

    nuget pack nuget\Khala.Messaging.Abstraction.nuspec

    nuget pack nuget\Khala.Messaging.Azure.nuspec
test:
  assemblies: '**\*.tests.dll'
artifacts:
- path: Khala.Messaging**.nupkg